# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'door_editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 568)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree = QtWidgets.QTreeWidget(self.splitter)
        self.tree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tree.setAlternatingRowColors(True)
        self.tree.setRootIsDecorated(True)
        self.tree.setUniformRowHeights(False)
        self.tree.setAllColumnsShowFocus(True)
        self.tree.setObjectName("tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tree.headerItem().setText(0, _translate("Form", "Field"))
        self.tree.headerItem().setText(1, _translate("Form", "Value"))
        __sortingEnabled = self.tree.isSortingEnabled()
        self.tree.setSortingEnabled(False)
        self.tree.topLevelItem(0).setText(0, _translate("Form", "Basic"))
        self.tree.topLevelItem(0).child(0).setText(0, _translate("Form", "Script Tag"))
        self.tree.topLevelItem(0).child(1).setText(0, _translate("Form", "Template"))
        self.tree.topLevelItem(0).child(2).setText(0, _translate("Form", "Dialog"))
        self.tree.topLevelItem(0).child(3).setText(0, _translate("Form", "Appearance"))
        self.tree.topLevelItem(1).setText(0, _translate("Form", "Name"))
        self.tree.topLevelItem(1).child(0).setText(0, _translate("Form", "TLK Reference"))
        self.tree.topLevelItem(1).child(1).setText(0, _translate("Form", "TLK Text"))
        self.tree.topLevelItem(1).child(2).setText(0, _translate("Form", "English"))
        self.tree.topLevelItem(1).child(3).setText(0, _translate("Form", "French"))
        self.tree.topLevelItem(1).child(4).setText(0, _translate("Form", "German"))
        self.tree.topLevelItem(1).child(5).setText(0, _translate("Form", "Italian"))
        self.tree.topLevelItem(1).child(6).setText(0, _translate("Form", "Spanish"))
        self.tree.topLevelItem(1).child(7).setText(0, _translate("Form", "Polish"))
        self.tree.topLevelItem(1).child(8).setText(0, _translate("Form", "Korean"))
        self.tree.topLevelItem(2).setText(0, _translate("Form", "Advanced"))
        self.tree.topLevelItem(2).child(0).setText(0, _translate("Form", "State"))
        self.tree.topLevelItem(2).child(1).setText(0, _translate("Form", "Faction"))
        self.tree.topLevelItem(3).setText(0, _translate("Form", "Other"))
        self.tree.topLevelItem(3).child(0).setText(0, _translate("Form", "Fortitude"))
        self.tree.topLevelItem(3).child(1).setText(0, _translate("Form", "Reflex"))
        self.tree.topLevelItem(3).child(2).setText(0, _translate("Form", "Will"))
        self.tree.topLevelItem(3).child(3).setText(0, _translate("Form", "Health"))
        self.tree.topLevelItem(3).child(4).setText(0, _translate("Form", "Hardness"))
        self.tree.topLevelItem(4).setText(0, _translate("Form", "Flags"))
        self.tree.topLevelItem(4).child(0).setText(0, _translate("Form", "Plot"))
        self.tree.topLevelItem(4).child(1).setText(0, _translate("Form", "Interruptable"))
        self.tree.topLevelItem(4).child(2).setText(0, _translate("Form", "Invincible"))
        self.tree.topLevelItem(4).child(3).setText(0, _translate("Form", "Static"))
        self.tree.topLevelItem(5).setText(0, _translate("Form", "Scripts"))
        self.tree.topLevelItem(5).child(0).setText(0, _translate("Form", "Routine"))
        self.tree.topLevelItem(5).child(1).setText(0, _translate("Form", "Used"))
        self.tree.topLevelItem(5).child(2).setText(0, _translate("Form", "Opened"))
        self.tree.topLevelItem(5).child(3).setText(0, _translate("Form", "Closed"))
        self.tree.topLevelItem(5).child(4).setText(0, _translate("Form", "Unlocked"))
        self.tree.topLevelItem(5).child(5).setText(0, _translate("Form", "Locked"))
        self.tree.topLevelItem(5).child(6).setText(0, _translate("Form", "Failed"))
        self.tree.topLevelItem(5).child(7).setText(0, _translate("Form", "Attacked Physically"))
        self.tree.topLevelItem(5).child(8).setText(0, _translate("Form", "Attacked Ability"))
        self.tree.topLevelItem(5).child(9).setText(0, _translate("Form", "Damaged"))
        self.tree.topLevelItem(5).child(10).setText(0, _translate("Form", "Death"))
        self.tree.topLevelItem(5).child(11).setText(0, _translate("Form", "Disarmed"))
        self.tree.topLevelItem(5).child(12).setText(0, _translate("Form", "Triggered"))
        self.tree.topLevelItem(5).child(13).setText(0, _translate("Form", "Custom"))
        self.tree.topLevelItem(6).setText(0, _translate("Form", "Trap"))
        self.tree.topLevelItem(6).child(0).setText(0, _translate("Form", "Is Trap"))
        self.tree.topLevelItem(6).child(1).setText(0, _translate("Form", "One-Shot"))
        self.tree.topLevelItem(6).child(2).setText(0, _translate("Form", "Findable"))
        self.tree.topLevelItem(6).child(3).setText(0, _translate("Form", "Disarmable"))
        self.tree.topLevelItem(6).child(4).setText(0, _translate("Form", "Detection DC"))
        self.tree.topLevelItem(6).child(5).setText(0, _translate("Form", "Disarm DC"))
        self.tree.topLevelItem(6).child(6).setText(0, _translate("Form", "Trap Type"))
        self.tree.topLevelItem(7).setText(0, _translate("Form", "Lock"))
        self.tree.topLevelItem(7).child(0).setText(0, _translate("Form", "Is Locked"))
        self.tree.topLevelItem(7).child(1).setText(0, _translate("Form", "Lockable"))
        self.tree.topLevelItem(7).child(2).setText(0, _translate("Form", "Requires Key"))
        self.tree.topLevelItem(7).child(3).setText(0, _translate("Form", "Remove Key"))
        self.tree.topLevelItem(7).child(4).setText(0, _translate("Form", "Key Tag"))
        self.tree.topLevelItem(7).child(5).setText(0, _translate("Form", "Unlock DC"))
        self.tree.topLevelItem(7).child(6).setText(0, _translate("Form", "Lock DC"))
        self.tree.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
