# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(735, 457)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.items_tree = QtWidgets.QTreeWidget(self.splitter_2)
        self.items_tree.setObjectName("items_tree")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.equipment_tabs = QtWidgets.QTabWidget(self.splitter)
        self.equipment_tabs.setTabBarAutoHide(False)
        self.equipment_tabs.setObjectName("equipment_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.implant_label = QtWidgets.QLabel(self.tab)
        self.implant_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.implant_label.setObjectName("implant_label")
        self.verticalLayout_14.addWidget(self.implant_label)
        self.implant_edit = QtWidgets.QLineEdit(self.tab)
        self.implant_edit.setObjectName("implant_edit")
        self.verticalLayout_14.addWidget(self.implant_edit)
        self.implant_name = QtWidgets.QLineEdit(self.tab)
        self.implant_name.setEnabled(False)
        self.implant_name.setReadOnly(True)
        self.implant_name.setObjectName("implant_name")
        self.verticalLayout_14.addWidget(self.implant_name)
        self.gridLayout.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.head_label = QtWidgets.QLabel(self.tab)
        self.head_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.head_label.setObjectName("head_label")
        self.verticalLayout_17.addWidget(self.head_label)
        self.head_edit = QtWidgets.QLineEdit(self.tab)
        self.head_edit.setObjectName("head_edit")
        self.verticalLayout_17.addWidget(self.head_edit)
        self.head_name = QtWidgets.QLineEdit(self.tab)
        self.head_name.setEnabled(False)
        self.head_name.setReadOnly(True)
        self.head_name.setObjectName("head_name")
        self.verticalLayout_17.addWidget(self.head_name)
        self.gridLayout.addLayout(self.verticalLayout_17, 0, 1, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gauntlet_label = QtWidgets.QLabel(self.tab)
        self.gauntlet_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.gauntlet_label.setObjectName("gauntlet_label")
        self.verticalLayout_15.addWidget(self.gauntlet_label)
        self.gauntlet_edit = QtWidgets.QLineEdit(self.tab)
        self.gauntlet_edit.setObjectName("gauntlet_edit")
        self.verticalLayout_15.addWidget(self.gauntlet_edit)
        self.gauntlet_name = QtWidgets.QLineEdit(self.tab)
        self.gauntlet_name.setEnabled(False)
        self.gauntlet_name.setReadOnly(True)
        self.gauntlet_name.setObjectName("gauntlet_name")
        self.verticalLayout_15.addWidget(self.gauntlet_name)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 2, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.leftarm_label = QtWidgets.QLabel(self.tab)
        self.leftarm_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.leftarm_label.setObjectName("leftarm_label")
        self.verticalLayout_13.addWidget(self.leftarm_label)
        self.leftarm_edit = QtWidgets.QLineEdit(self.tab)
        self.leftarm_edit.setObjectName("leftarm_edit")
        self.verticalLayout_13.addWidget(self.leftarm_edit)
        self.leftarm_name = QtWidgets.QLineEdit(self.tab)
        self.leftarm_name.setEnabled(False)
        self.leftarm_name.setReadOnly(True)
        self.leftarm_name.setObjectName("leftarm_name")
        self.verticalLayout_13.addWidget(self.leftarm_name)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 0, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.armor_label = QtWidgets.QLabel(self.tab)
        self.armor_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.armor_label.setObjectName("armor_label")
        self.verticalLayout_18.addWidget(self.armor_label)
        self.armor_edit = QtWidgets.QLineEdit(self.tab)
        self.armor_edit.setObjectName("armor_edit")
        self.verticalLayout_18.addWidget(self.armor_edit)
        self.armor_name = QtWidgets.QLineEdit(self.tab)
        self.armor_name.setEnabled(False)
        self.armor_name.setReadOnly(True)
        self.armor_name.setObjectName("armor_name")
        self.verticalLayout_18.addWidget(self.armor_name)
        self.gridLayout.addLayout(self.verticalLayout_18, 1, 1, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.rightarm_label = QtWidgets.QLabel(self.tab)
        self.rightarm_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.rightarm_label.setObjectName("rightarm_label")
        self.verticalLayout_16.addWidget(self.rightarm_label)
        self.rightarm_edit = QtWidgets.QLineEdit(self.tab)
        self.rightarm_edit.setObjectName("rightarm_edit")
        self.verticalLayout_16.addWidget(self.rightarm_edit)
        self.rightarm_name = QtWidgets.QLineEdit(self.tab)
        self.rightarm_name.setEnabled(False)
        self.rightarm_name.setReadOnly(True)
        self.rightarm_name.setObjectName("rightarm_name")
        self.verticalLayout_16.addWidget(self.rightarm_name)
        self.gridLayout.addLayout(self.verticalLayout_16, 1, 2, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lefthand_label = QtWidgets.QLabel(self.tab)
        self.lefthand_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lefthand_label.setObjectName("lefthand_label")
        self.verticalLayout_19.addWidget(self.lefthand_label)
        self.lefthand_edit = QtWidgets.QLineEdit(self.tab)
        self.lefthand_edit.setObjectName("lefthand_edit")
        self.verticalLayout_19.addWidget(self.lefthand_edit)
        self.lefthand_name = QtWidgets.QLineEdit(self.tab)
        self.lefthand_name.setEnabled(False)
        self.lefthand_name.setReadOnly(True)
        self.lefthand_name.setObjectName("lefthand_name")
        self.verticalLayout_19.addWidget(self.lefthand_name)
        self.gridLayout.addLayout(self.verticalLayout_19, 2, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.belt_label = QtWidgets.QLabel(self.tab)
        self.belt_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.belt_label.setObjectName("belt_label")
        self.verticalLayout_20.addWidget(self.belt_label)
        self.belt_edit = QtWidgets.QLineEdit(self.tab)
        self.belt_edit.setObjectName("belt_edit")
        self.verticalLayout_20.addWidget(self.belt_edit)
        self.belt_name = QtWidgets.QLineEdit(self.tab)
        self.belt_name.setEnabled(False)
        self.belt_name.setReadOnly(True)
        self.belt_name.setObjectName("belt_name")
        self.verticalLayout_20.addWidget(self.belt_name)
        self.gridLayout.addLayout(self.verticalLayout_20, 2, 1, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.righthand_label = QtWidgets.QLabel(self.tab)
        self.righthand_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.righthand_label.setObjectName("righthand_label")
        self.verticalLayout_21.addWidget(self.righthand_label)
        self.righthand_edit = QtWidgets.QLineEdit(self.tab)
        self.righthand_edit.setObjectName("righthand_edit")
        self.verticalLayout_21.addWidget(self.righthand_edit)
        self.righthand_name = QtWidgets.QLineEdit(self.tab)
        self.righthand_name.setEnabled(False)
        self.righthand_name.setReadOnly(True)
        self.righthand_name.setObjectName("righthand_name")
        self.verticalLayout_21.addWidget(self.righthand_name)
        self.gridLayout.addLayout(self.verticalLayout_21, 2, 2, 1, 1)
        self.equipment_tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.creature3_label = QtWidgets.QLabel(self.tab_2)
        self.creature3_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.creature3_label.setObjectName("creature3_label")
        self.verticalLayout_24.addWidget(self.creature3_label)
        self.creature3_edit = QtWidgets.QLineEdit(self.tab_2)
        self.creature3_edit.setObjectName("creature3_edit")
        self.verticalLayout_24.addWidget(self.creature3_edit)
        self.creature3_name = QtWidgets.QLineEdit(self.tab_2)
        self.creature3_name.setEnabled(False)
        self.creature3_name.setReadOnly(True)
        self.creature3_name.setObjectName("creature3_name")
        self.verticalLayout_24.addWidget(self.creature3_name)
        self.gridLayout_3.addLayout(self.verticalLayout_24, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.creature1_label = QtWidgets.QLabel(self.tab_2)
        self.creature1_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.creature1_label.setObjectName("creature1_label")
        self.verticalLayout_22.addWidget(self.creature1_label)
        self.creature1_edit = QtWidgets.QLineEdit(self.tab_2)
        self.creature1_edit.setObjectName("creature1_edit")
        self.verticalLayout_22.addWidget(self.creature1_edit)
        self.creature1_name = QtWidgets.QLineEdit(self.tab_2)
        self.creature1_name.setEnabled(False)
        self.creature1_name.setReadOnly(True)
        self.creature1_name.setObjectName("creature1_name")
        self.verticalLayout_22.addWidget(self.creature1_name)
        self.gridLayout_3.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.creature2_label = QtWidgets.QLabel(self.tab_2)
        self.creature2_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.creature2_label.setObjectName("creature2_label")
        self.verticalLayout_23.addWidget(self.creature2_label)
        self.creature2_edit = QtWidgets.QLineEdit(self.tab_2)
        self.creature2_edit.setObjectName("creature2_edit")
        self.verticalLayout_23.addWidget(self.creature2_edit)
        self.creature2_name = QtWidgets.QLineEdit(self.tab_2)
        self.creature2_name.setEnabled(False)
        self.creature2_name.setReadOnly(True)
        self.creature2_name.setObjectName("creature2_name")
        self.verticalLayout_23.addWidget(self.creature2_name)
        self.gridLayout_3.addLayout(self.verticalLayout_23, 0, 1, 1, 1)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.hide_label = QtWidgets.QLabel(self.tab_2)
        self.hide_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.hide_label.setObjectName("hide_label")
        self.verticalLayout_25.addWidget(self.hide_label)
        self.hide_edit = QtWidgets.QLineEdit(self.tab_2)
        self.hide_edit.setObjectName("hide_edit")
        self.verticalLayout_25.addWidget(self.hide_edit)
        self.hide_name = QtWidgets.QLineEdit(self.tab_2)
        self.hide_name.setEnabled(False)
        self.hide_name.setReadOnly(True)
        self.hide_name.setObjectName("hide_name")
        self.verticalLayout_25.addWidget(self.hide_name)
        self.gridLayout_3.addLayout(self.verticalLayout_25, 1, 1, 1, 1)
        self.equipment_tabs.addTab(self.tab_2, "")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inventory_table = QtWidgets.QTableView(self.layoutWidget)
        self.inventory_table.setCornerButtonEnabled(True)
        self.inventory_table.setObjectName("inventory_table")
        self.verticalLayout.addWidget(self.inventory_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.layoutWidget)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout.addWidget(self.remove_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.equipment_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.items_tree.headerItem().setText(0, _translate("Form", "Name"))
        self.items_tree.headerItem().setText(1, _translate("Form", "ResRef"))
        self.implant_label.setText(_translate("Form", "Implant"))
        self.head_label.setText(_translate("Form", "Head"))
        self.gauntlet_label.setText(_translate("Form", "Gauntlet"))
        self.leftarm_label.setText(_translate("Form", "Left Arm"))
        self.armor_label.setText(_translate("Form", "Armor"))
        self.rightarm_label.setText(_translate("Form", "Right Arm"))
        self.lefthand_label.setText(_translate("Form", "Left Hand"))
        self.belt_label.setText(_translate("Form", "Belt"))
        self.righthand_label.setText(_translate("Form", "Right Hand"))
        self.equipment_tabs.setTabText(self.equipment_tabs.indexOf(self.tab), _translate("Form", "Standard"))
        self.creature3_label.setText(_translate("Form", "Creature Item 3"))
        self.creature1_label.setText(_translate("Form", "Creature Item 1"))
        self.creature2_label.setText(_translate("Form", "Creature Item 2"))
        self.hide_label.setText(_translate("Form", "Hide"))
        self.equipment_tabs.setTabText(self.equipment_tabs.indexOf(self.tab_2), _translate("Form", "Other"))
        self.add_button.setText(_translate("Form", "Add"))
        self.remove_button.setText(_translate("Form", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
