# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 568)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree = QtWidgets.QTreeWidget(self.splitter)
        self.tree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tree.setAlternatingRowColors(True)
        self.tree.setRootIsDecorated(True)
        self.tree.setUniformRowHeights(False)
        self.tree.setAllColumnsShowFocus(True)
        self.tree.setObjectName("tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tree.headerItem().setText(0, _translate("Form", "Field"))
        self.tree.headerItem().setText(1, _translate("Form", "Value"))
        __sortingEnabled = self.tree.isSortingEnabled()
        self.tree.setSortingEnabled(False)
        self.tree.topLevelItem(0).setText(0, _translate("Form", "Basic"))
        self.tree.topLevelItem(0).child(0).setText(0, _translate("Form", "Script Tag"))
        self.tree.topLevelItem(0).child(1).setText(0, _translate("Form", "Template"))
        self.tree.topLevelItem(0).child(2).setText(0, _translate("Form", "Base"))
        self.tree.topLevelItem(0).child(3).setText(0, _translate("Form", "Cost"))
        self.tree.topLevelItem(0).child(4).setText(0, _translate("Form", "Additional Cost"))
        self.tree.topLevelItem(0).child(5).setText(0, _translate("Form", "Plot Item"))
        self.tree.topLevelItem(1).setText(0, _translate("Form", "Name"))
        self.tree.topLevelItem(1).child(0).setText(0, _translate("Form", "TLK Reference"))
        self.tree.topLevelItem(1).child(1).setText(0, _translate("Form", "TLK Text"))
        self.tree.topLevelItem(1).child(2).setText(0, _translate("Form", "English"))
        self.tree.topLevelItem(1).child(3).setText(0, _translate("Form", "French"))
        self.tree.topLevelItem(1).child(4).setText(0, _translate("Form", "German"))
        self.tree.topLevelItem(1).child(5).setText(0, _translate("Form", "Italian"))
        self.tree.topLevelItem(1).child(6).setText(0, _translate("Form", "Spanish"))
        self.tree.topLevelItem(1).child(7).setText(0, _translate("Form", "Polish"))
        self.tree.topLevelItem(1).child(8).setText(0, _translate("Form", "Korean"))
        self.tree.topLevelItem(2).setText(0, _translate("Form", "Description"))
        self.tree.topLevelItem(2).child(0).setText(0, _translate("Form", "TLK Reference"))
        self.tree.topLevelItem(2).child(1).setText(0, _translate("Form", "TLK Text"))
        self.tree.topLevelItem(2).child(2).setText(0, _translate("Form", "English"))
        self.tree.topLevelItem(2).child(3).setText(0, _translate("Form", "French"))
        self.tree.topLevelItem(2).child(4).setText(0, _translate("Form", "German"))
        self.tree.topLevelItem(2).child(5).setText(0, _translate("Form", "Italian"))
        self.tree.topLevelItem(2).child(6).setText(0, _translate("Form", "Spanish"))
        self.tree.topLevelItem(2).child(7).setText(0, _translate("Form", "Polish"))
        self.tree.topLevelItem(2).child(8).setText(0, _translate("Form", "Korean"))
        self.tree.topLevelItem(3).setText(0, _translate("Form", "Advanced"))
        self.tree.topLevelItem(3).child(0).setText(0, _translate("Form", "Palette ID"))
        self.tree.topLevelItem(3).child(1).setText(0, _translate("Form", "Upgrade Level"))
        self.tree.topLevelItem(3).child(2).setText(0, _translate("Form", "Charges"))
        self.tree.topLevelItem(3).child(3).setText(0, _translate("Form", "Stack Size"))
        self.tree.topLevelItem(3).child(4).setText(0, _translate("Form", "Model Variation"))
        self.tree.topLevelItem(3).child(5).setText(0, _translate("Form", "Body Variation"))
        self.tree.topLevelItem(3).child(6).setText(0, _translate("Form", "Texture Variation"))
        self.tree.topLevelItem(4).setText(0, _translate("Form", "Properties"))
        self.tree.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
