# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creature_editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(939, 568)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree = QtWidgets.QTreeWidget(self.splitter)
        self.tree.setAlternatingRowColors(False)
        self.tree.setRootIsDecorated(True)
        self.tree.setUniformRowHeights(True)
        self.tree.setAllColumnsShowFocus(True)
        self.tree.setObjectName("tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tree.headerItem().setText(0, _translate("Form", "Field"))
        self.tree.headerItem().setText(1, _translate("Form", "Value"))
        __sortingEnabled = self.tree.isSortingEnabled()
        self.tree.setSortingEnabled(False)
        self.tree.topLevelItem(0).setText(0, _translate("Form", "Basic"))
        self.tree.topLevelItem(0).child(0).setText(0, _translate("Form", "Script Tag"))
        self.tree.topLevelItem(0).child(1).setText(0, _translate("Form", "Template"))
        self.tree.topLevelItem(0).child(2).setText(0, _translate("Form", "Dialog"))
        self.tree.topLevelItem(0).child(3).setText(0, _translate("Form", "Name (English)"))
        self.tree.topLevelItem(0).child(4).setText(0, _translate("Form", "Name (StrRef)"))
        self.tree.topLevelItem(0).child(5).setText(0, _translate("Form", "TLK Entry"))
        self.tree.topLevelItem(0).child(6).setText(0, _translate("Form", "Alignment"))
        self.tree.topLevelItem(0).child(7).setText(0, _translate("Form", "Appearance"))
        self.tree.topLevelItem(0).child(8).setText(0, _translate("Form", "Body Bag"))
        self.tree.topLevelItem(0).child(9).setText(0, _translate("Form", "Class"))
        self.tree.topLevelItem(0).child(10).setText(0, _translate("Form", "Level"))
        self.tree.topLevelItem(1).setText(0, _translate("Form", "Advanced"))
        self.tree.topLevelItem(1).child(0).setText(0, _translate("Form", "Race"))
        self.tree.topLevelItem(1).child(1).setText(0, _translate("Form", "Subrace"))
        self.tree.topLevelItem(1).child(2).setText(0, _translate("Form", "Phenotype"))
        self.tree.topLevelItem(1).child(3).setText(0, _translate("Form", "Perception"))
        self.tree.topLevelItem(1).child(4).setText(0, _translate("Form", "Soundset"))
        self.tree.topLevelItem(1).child(5).setText(0, _translate("Form", "Faction"))
        self.tree.topLevelItem(1).child(6).setText(0, _translate("Form", "Gender"))
        self.tree.topLevelItem(1).child(7).setText(0, _translate("Form", "Speed"))
        self.tree.topLevelItem(1).child(8).setText(0, _translate("Form", "Portrait"))
        self.tree.topLevelItem(2).setText(0, _translate("Form", "Attributes"))
        self.tree.topLevelItem(2).child(0).setText(0, _translate("Form", "Strength"))
        self.tree.topLevelItem(2).child(1).setText(0, _translate("Form", "Dexterity"))
        self.tree.topLevelItem(2).child(2).setText(0, _translate("Form", "Constitution"))
        self.tree.topLevelItem(2).child(3).setText(0, _translate("Form", "Intelligence"))
        self.tree.topLevelItem(2).child(4).setText(0, _translate("Form", "Wisdom"))
        self.tree.topLevelItem(2).child(5).setText(0, _translate("Form", "Charisma"))
        self.tree.topLevelItem(3).setText(0, _translate("Form", "Skills"))
        self.tree.topLevelItem(3).child(0).setText(0, _translate("Form", "Computer Use"))
        self.tree.topLevelItem(3).child(1).setText(0, _translate("Form", "Demolitions"))
        self.tree.topLevelItem(3).child(2).setText(0, _translate("Form", "Stealth"))
        self.tree.topLevelItem(3).child(3).setText(0, _translate("Form", "Awareness"))
        self.tree.topLevelItem(3).child(4).setText(0, _translate("Form", "Persuade"))
        self.tree.topLevelItem(3).child(5).setText(0, _translate("Form", "Repair"))
        self.tree.topLevelItem(3).child(6).setText(0, _translate("Form", "Security"))
        self.tree.topLevelItem(3).child(7).setText(0, _translate("Form", "Treat Injury"))
        self.tree.topLevelItem(4).setText(0, _translate("Form", "Other"))
        self.tree.topLevelItem(4).child(0).setText(0, _translate("Form", "Challenge Rating"))
        self.tree.topLevelItem(4).child(1).setText(0, _translate("Form", "Natural AC"))
        self.tree.topLevelItem(4).child(2).setText(0, _translate("Form", "Fortitude"))
        self.tree.topLevelItem(4).child(3).setText(0, _translate("Form", "Reflex"))
        self.tree.topLevelItem(4).child(4).setText(0, _translate("Form", "Will"))
        self.tree.topLevelItem(4).child(5).setText(0, _translate("Form", "Health"))
        self.tree.topLevelItem(4).child(6).setText(0, _translate("Form", "Force"))
        self.tree.topLevelItem(5).setText(0, _translate("Form", "Flags"))
        self.tree.topLevelItem(5).child(0).setText(0, _translate("Form", "Invincible"))
        self.tree.topLevelItem(5).child(1).setText(0, _translate("Form", "Is PC"))
        self.tree.topLevelItem(5).child(2).setText(0, _translate("Form", "Disarmable"))
        self.tree.topLevelItem(5).child(3).setText(0, _translate("Form", "Doesn\'t Die"))
        self.tree.topLevelItem(5).child(4).setText(0, _translate("Form", "Plot"))
        self.tree.topLevelItem(5).child(5).setText(0, _translate("Form", "Doesn\'t Face PC"))
        self.tree.topLevelItem(5).child(6).setText(0, _translate("Form", "Interruptable"))
        self.tree.topLevelItem(5).child(7).setText(0, _translate("Form", "Interactable"))
        self.tree.topLevelItem(6).setText(0, _translate("Form", "Scripts"))
        self.tree.topLevelItem(6).child(0).setText(0, _translate("Form", "OnHeartbeat"))
        self.tree.topLevelItem(6).child(1).setText(0, _translate("Form", "OnNotice"))
        self.tree.topLevelItem(6).child(2).setText(0, _translate("Form", "OnSpellAt"))
        self.tree.topLevelItem(6).child(3).setText(0, _translate("Form", "OnAttacked"))
        self.tree.topLevelItem(6).child(4).setText(0, _translate("Form", "OnDamaged"))
        self.tree.topLevelItem(6).child(5).setText(0, _translate("Form", "OnDisturbed"))
        self.tree.topLevelItem(6).child(6).setText(0, _translate("Form", "OnEndRound"))
        self.tree.topLevelItem(6).child(7).setText(0, _translate("Form", "OnEndDialog"))
        self.tree.topLevelItem(6).child(8).setText(0, _translate("Form", "OnDialog"))
        self.tree.topLevelItem(6).child(9).setText(0, _translate("Form", "OnSpawn"))
        self.tree.topLevelItem(6).child(10).setText(0, _translate("Form", "OnDeath"))
        self.tree.topLevelItem(6).child(11).setText(0, _translate("Form", "OnBlocked"))
        self.tree.topLevelItem(6).child(12).setText(0, _translate("Form", "OnUserDefined"))
        self.tree.topLevelItem(7).setText(0, _translate("Form", "Feats"))
        self.tree.topLevelItem(8).setText(0, _translate("Form", "Powers"))
        self.tree.topLevelItem(9).setText(0, _translate("Form", "Inventory"))
        self.tree.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
